#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Tomoki sato
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans1 = 0.0
ans2 = 0.0
ans3 = 1.0
ans4 = 1.0

for line in sys.stdin:
    num = float(line)
    ans1 += num
    ans2 -= num
    ans3 *= num
    ans4 /= num

print(ans1)
print(ans2)
print(ans3)
print(ans4)
